### ISSUE TITLE
[Bug]: LÖVE Potion doesn't upscale to 1080p correctly

### ISSUE THREAD

**Issue by HTV04** [lovebrew/LovePotion#152]
### Software Version

2.2.0 (Latest)

### What Happened?

When running LÖVE Potion in docked mode, it runs at 1080p, but it draws a 720p canvas in the top-left corner. The `love.graphics` callbacks (such as `love.graphics.getWidth`) also return values for a 720p resolution.

### What was Expected?

LÖVE Potion and the `love.graphics` callbacks should adapt to a 1080p resolution in docked mode.

### Code to Reproduce

```Lua
-- Prints "1280" instead of "1920"
print(love.graphics.getWidth())
```

### Console

Nintendo Switch

### Firmware Version(s)

12.0.1

### Custom Firmware Version

0.19.3

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Some initial debugging indicates the system *does* detect it is in docked mode on boot. However, due to.. something it does not not resize the Graphics callbacks accordingly.

I'll keep looking through and see what I have to fix. Since the code doesn't entirely match LÖVE (though not everything can and will, but this should be doable) that may be why I have some out of order logic.
