### ISSUE TITLE
[Feature Request]: Compatibility

### ISSUE THREAD

**Issue by fontire** [lovebrew/LovePotion#158]
### Enhancement Details

Add features needed to run some games or samples

### Solution

Allow more games/samples to work on Switch

### Additional Context

I have run into several compatibility problems, trying out Love programs (from the website/forum) on Switch.
For example, this seems to be missing:

```
love.window.getMode()
```

Can that be added? Would it be useful to make a list of missing calls?

**Comment by TurtleP** [comment]
I think a lot of the issues that come from this is expecting LÖVE Potion to be 100% compatible with LÖVE itself. The goal is definitely to maintain as much compatibility as possible, but some things either don't apply or just can't be compatible.

Specifically with `love.window.getMode`, it is doable, but even `love.window.setMode` is a dummy (fake/empty) call because for the most part, the console is in a fixed resolution. I'd rather not have these kinds of situations, honestly, because even if I have the empty call and it doesn't error, people will ask why it doesn't actually work.

In either case, the Wiki does maintain a [healthy portion of the implemented API](https://lovebrew.org/#/api/love). If it's not there, it's not implemented.

**Comment by fontire** [comment]
Ah, I see. Thank you.

What about `setVolume` for a source created with `love.audio.newSource`?

I tried it out and it doesn't have any effect. It should be possible to adjust the volume of different sources, right?

**Comment by TurtleP** [comment]
Yes, it should be possible. I'm not entirely sure why it might not work, looking at the code for it.

**Comment by fontire** [comment]
Thanks.

**Comment by fontire** [comment]
I also ran into a crash using `love.graphics.polygon`. If you have time to look at it, let me know (and how to send the script to you).

**Comment by piepie62** [comment]
Upload it here and I'll take a look. I'm the one that built most of the implementation for that (assuming you're talking about the 3DS)

**Comment by fontire** [comment]
> 
> 
> Upload it here and I'll take a look. I'm the one that built most of the implementation for that (assuming you're talking about the 3DS)

I'm on the Switch.

I put a comment under the line that crashes
https://bsd.to/HHFG

**Comment by piepie62** [comment]
*Pretty* sure this is a logic error; cursory reading makes it seem like that's not a convex polygon. Perhaps on the last point you meant it to be tx rather than tx+edge? I'll see what I can do about the crash, but I *believe* that would be your issue. Debugging on Switch is unfortunately quite difficult until SciresM finishes Atmosphère's tma2 reimplementation

**Comment by fontire** [comment]
I wouldn't be surprised if it's a user/logic error, either. It works on my computer but maybe it's compensating?

I borrowed that drawing script from the Love forums and it worked until I started drawing across the whole screen.

**Comment by fontire** [comment]
@piepie62 I tried `tx` instead of `tx+edge` but that didn't do it.

By the way, I started a repo to test compatibility and provide some examples:
https://github.com/fontire/LovePotionBook

I'd like to get Dialove working.
