### ISSUE TITLE
[Bug]: love.window.showMessageBox issues

### ISSUE THREAD

**Issue by TurtleP** [lovebrew/lovepotion#161]
### Software Version

2.2.0 (Latest)

### What Happened?

Calling LÖVE API functions within wrap_window.lua seems to cause issues in certain situations. The source of the issue hasn't entirely been tracked down yet, though.

### What was Expected?

The function call shouldn't interfere with running games.

### Code to Reproduce

```Lua
N/A
```

### Console

Both

### Firmware Version(s)

12.0.1 / 11.14.0-46U

### Custom Firmware Version

0.19.3 / 10.2.1

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
I'm not really sure the issue is so much `wrap_window.lua` calling `love.draw`. If memory serves, I did this to preserve what is rendered below the messagebox. However, I am looking into some alternative methods to handle all the logic.

Something akin to `hump.gamestate` and how it hooks into LÖVE's callbacks.

**Comment by HTV04** [comment]
> I'm not really sure the issue is so much `wrap_window.lua` calling `love.draw`. If memory serves, I did this to preserve what is rendered below the messagebox. However, I am looking into some alternative methods to handle all the logic.
> 
> Something akin to `hump.gamestate` and how it hooks into LÖVE's callbacks.

wrap_window.lua already does something akin to hump.gamestate by running its own loop and calling love.draw from the "previous" state in its own draw loop.

However, this is a flawed approach, because it assumes love.draw does nothing else than draw the screen, not taking into account values that may not be loaded yet, or other code called when the screen is ready to be drawn.

I see what you're trying to do, but calling love.draw is definitely not a good way to draw the current frame behind the message box. Maybe you can take a screenshot of what's on screen before loading the message box somehow, and draw the message box on top of that?

**Comment by TurtleP** [comment]
Hm.. I think I'll want to verify that the issue even stems from `love.draw` first. Any and all variables inside of wrap_window.lua happen to be contained within that script as locals. Although.. I think I see what you  mean.

In the given scenario of your game, `love.draw()` needs a global variable constructed at runtime. I don't really recall, but it might not have been initialized yet, hence the fact when it *does* get called by `wrap_window.lua` it flips out since your font is indeed `nil`.

I'm not sure about a screenshot of the screen. That's definitely out of the league for 3DS. I think, at least. I'll need to discuss how the heck screenshots might work on there and even adding the ImageData class to deal with it. Although I don't want this to take longer than it has to fix, even though 2.2.0 is officially waiting for some updates to libctru, citro3d, and citro2d.

**Comment by HTV04** [comment]
> Hm.. I think I'll want to verify that the issue even stems from love.draw first. Any and all variables inside of wrap_window.lua happen to be contained within that script as locals.

Looking at the code and the issue with my game, I'm 99.9% sure that the issue is with calling the love.draw() function, everything else seems to be fine and independent from anything else (aside from the fact that it ignores canvases, so the message box will draw to a canvas if it isn't set to not do so beforehand).

> I'm not sure about a screenshot of the screen. That's definitely out of the league for 3DS. I think, at least. I'll need to discuss how the heck screenshots might work on there and even adding the ImageData class to deal with it.

I feel that the best solution would be for the message box to be a completely independent loop from everything else, drawing nothing behind the message box. It would look less aesthetically pleasing, but it would also be the easiest and most compatible solution.
