### ISSUE TITLE
[Feature Request]: love.graphics.newShader

### ISSUE THREAD

**Issue by Cambriaware** [lovebrew/lovepotion#169]
### Enhancement Details

Tried mucking around with g3d and ive found that it wont load as love.graphics.newShader does not exist (i think...)

### Solution

Implement love.graphics.newShader functionality into love potion

### Additional Context

None...

**Comment by TurtleP** [comment]
Correct, the function does not exist, really. On Nintendo Switch it does, but it is not hooked up to the Lua end of things. Ideally I would like to eventually have the 3DS version running pure citro3d instead of relying on citro2d (or if this is also a thing in citro2d) and allow custom shaders there. However, overall, I don't know the best course of action.

Shaders on 3DS are very complicated, to a degree, so users would need to learn [the picasso shader assembly](https://github.com/devkitPro/picasso/blob/master/Manual.md) and I doubt many users would want to mess with it.

Shaders on Switch aren't equivalent to the ones LÖVE have, given there's 3 separate ones: color, texture, and transform. There isn't plans to make them into one big übershader like LÖVE and the syntax, while is still GL-based, is much more complex.

Generally speaking, shaders are not my forte and trying to get something like what LÖVE has is a bit much for me right now. It's not like I haven't given it any thought, it's mainly I don't have a good course of action to handle this.

**Comment by ACIDULATED** [comment]
> Generally speaking, shaders are not my forte and trying to get something like what LÖVE has is a bit much for me right now. It's not like I haven't given it any thought, it's mainly I don't have a good course of action to handle this.

This would be extremely helpful. Please consider it. I'm working on a 3D game and it would be extremely helpful to use a 3d engine instead of writing my own without any shaders. This is a must-have. Please consider it.

**Comment by TurtleP** [comment]
While I'm looking at 3.0 for a lot of changes, I don't think Shaders will really make it in. We now have Wii U support and you'll need to understand the shader assembly stuff for that stuff to work. I still don't think users will want to learn anything other than glsl syntax and only the Switch has that.

That said, @ACIDULATED I also don't think having shader functionality is absolutely crucial to making a 3d game. It would definitely make it easier, but there's ways to do it without a shader, though I'm no expert on these matters. Closing this for now.
